// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// circacf
NumericVector circacf(NumericVector x, unsigned int tau_max);
RcppExport SEXP prodyna_circacf(SEXP xSEXP, SEXP tau_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type tau_max(tau_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(circacf(x, tau_max));
    return rcpp_result_gen;
END_RCPP
}
// fastacf
NumericVector fastacf(NumericVector x, unsigned int tau_max);
RcppExport SEXP prodyna_fastacf(SEXP xSEXP, SEXP tau_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type tau_max(tau_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(fastacf(x, tau_max));
    return rcpp_result_gen;
END_RCPP
}
