
#' Read dihedrals.
#'
#' Read the columns corresponding to the \eqn{\phi} and \eqn{\psi} angles of the
#' given residues.
#'
#' @param dihedrals Character, name of the .dih file containing the dihedral
#'  angles.
#' @param dihedralsInfo Character, name of the .dih.info file as generated by
#'  \code{\link{generate.dihedrals}}. If \code{NULL} the filename is assumed to
#'  be <dihedrals>.info
#' @param resnos Numeric vector, residue numbers for which dihedral angles
#'  should be read. If \code{NULL} (default) read dihedrals for all residues.
#' @return A data.frame with \eqn{\phi} and \eqn{\psi} angles.
#' @export
read.dihedrals <- function(dihedrals, dihedralsInfo=NULL, resnos=NULL) {

  # Assume default naming
  if (is.null(dihedralsInfo)) {
    dihedralsInfo <- paste(dihedrals, ".info", sep="")
  }

  dInf <- read.dihedrals.info(dihedralsInfo)
  storedResnos <- (1:dInf$nRes)[-dInf$skippedResnos]

  if (is.null(resnos)){
    # Read all dihedrals.
    dih <- data.table::fread(dihedrals,
                             verbose=FALSE,
                             showProgress=FALSE)
    resnos <- storedResnos

  } else if (!all(resnos %in% storedResnos)) {
    stop(paste("read.dihedrals: File", dihedrals,
               "does not contain all of the requested residues."))
  } else {
    # Compute the columns corresponding to the given residue numbers.
    cols <- do.call("c", lapply(resnos,
                                function(i){c(2*(which(i==storedResnos))-1,
                                              2*(which(i==storedResnos)))}))
    dih <- data.table::fread(dihedrals,
                             select=cols,
                             verbose=FALSE,
                             showProgress=FALSE)
  }
  colnames(dih) <- paste(c("phi", "psi"), rep(resnos, each=2), sep="")
  return(dih)
}

#' Read dihedrals information.
#'
#' Reads a .dih.info file as generated by \code{\link{write.dihedrals.info}}.
#'
#' @param dihedralsInfo Character, name of the .dih.info file.
#' @export
#' @importFrom data.table fread
#' @return named list with elements \code{ref}, \code{traj}, \code{nRes},
#'   \code{skippedResnos}
read.dihedrals.info <- function(dihedralsInfo) {

  onError <- function(c) {stop(msg("format", dihedralsInfo))}

  tryCatch(
    info <- fread(dihedralsInfo, sep="\t", header=F, verbose=F, select=c(2)),
    error   = onError,
    warning = onError
  )

  ref  <- info[[1,1]]
  traj <- info[[2,1]]

  tryCatch(
    {
      nRes          <- as.numeric(info[[3,1]])
      skippedResnos <- as.numeric(strsplit(info[[4,1]], split=" ")[[1]])
    },
    error   = onError,
    warning = onError
  )

  return(list(ref=ref, traj=traj, nRes=nRes, skippedResnos = skippedResnos))
}

#' Write dihedrals infomation.
#'
#' Writes a .dih.info file with the following format (all fields are separated
#' by a single space):
#' \preformatted{
#' reference <normalized path to .pdb file>
#' trajectory <normalized path to .xtc file>r
#' nResiduals <integer>
#' skippedResiduals <space separated integers increasingly ordered>
#' }
#'
#' @param ref Character, name of the PDB file describing the reference structure.
#' @param traj Character, name of the XTC file describing the trajectory.
#' @param nRes Numeric, largest residue index
#' @param skipCA Numeric vector, C\eqn{_\alpha} indices to be skipped in
#'   increasing order.
#' @param fname Character, filename that should end in .dih.inf \cr
#'   If \code{NULL} (default) the file is named <traj>.dih.info
#' @export
write.dihedrals.info <- function(ref, traj, nRes, skipCA, fname=NULL) {
  if (is.null(fname)) {
    fname <- paste(traj, ".dih.info", sep="")
  }
  write(paste(paste("reference",  ref, sep="\t"),
              paste("trajectory", traj, sep="\t"),
              paste("nResiduals", nRes, sep="\t"),
              paste("skippedResiduals", paste(skipCA, collapse=" "), sep="\t"),
              sep = "\n"),
        fname)
}

#' Cumulative fluctuations.
#'
#' TODO: description
#'
#' @param vals Character or numeric vector, either name of the .val/.valn file
#'  or vector of eigenvalues.
#' @return cumulative fluctuations
#' @export
read.cumFlucts <- function(vals) {

  if (is.character(vals)) {
    vals <- data.table::fread(vals)
    vals <- vals$V1
  }
  return(cumsum(vals/max(vals)))
}



