
#
# TODO: package documentation & license(-file)
#

#' warning messages
.warnings <- list("no_init" =
                    "No project has been initialized so far. Call prodyna::initialize(...)",
                  "diverging_path" =
                    "Current directory and project paths diverge. Resetting current directory to project path")


#### handling external binaries

.default_binaries <- list("gmx"="/usr/local/gromacs/bin/gmx",
                          "fastpca"="/usr/local/bin/fastpca",
                          "clustering"="/usr/local/bin/clustering",
                          "bash"="/bin/bash",
                          "awk"="/usr/bin/awk",
                          "paste"="/usr/bin/paste")

.binaries <- new.env()

#' Set path to binary
#'
#' @param name Name of the binary
#' @param path Absolute system path to binary
#' @examples
#' set.binary("bash", "/bin/bash")
#' @export
set.binary <- function(name, path) {
  assign(name, path, envir=.binaries)
}

#' Get path to binary
#'
#' @param name Name of the binary
#' @export
get.binary <- function(name) {
  if (exists(name, envir=.binaries, inherits=FALSE)) {
    get(name, envir=.binaries)
  } else {
    .default_binaries[[name]]
  }
}

#' List names and paths to binaries called by prodyna
#' @export
list.binaries <- function() {
  lapply(names(.default_binaries), function(n) {
    c(n, get.binary(n))
  })
}


#### project management

#' Project cache
#'
#' Holds all project-related information.
#' Automatically updated by generator functions.
.project_cache <- new.env()

#' get project information
#'
#' @export
project <- function() {
  if (exists("project",
             envir=.project_cache,
             inherits=FALSE)) {
    get("project", envir=.project_cache)
  } else {
    warning(.warnings$no_init)
    NULL
  }
}

## project file detection

#' List reference structure files (.pdb)
.list.reference <- function() {
  list.files(pattern = "*.pdb")
}
#' List trajectory files (.xtc)
.list.traj <- function() {
  list.files(pattern = "*.xtc$")
}
#' List files with dihedral angles (.dih)
.list.dihedrals <- function() {
  list.files(pattern = "*.dih$")
}
#' List generic PCA files (cov, proj, etc.)
.list.PCA <- function(file_pattern) {
  PCA <- list()
  suffix <- c("proj", "cov", "vec", "val", "stats")
  suffix <- paste(rep(suffix, 2), c("", "n"), sep="")
  for (s in suffix) {
    PCA[[s]] <- list.files(pattern=paste(file_pattern,
                                         ".",
                                         s,
                                         "$",
                                         sep=""))
  }

  PCA
}
#' List specifically dPCA+ related files
.list.dPCAplus <- function() {
  .list.PCA("*.dih")
}
#' List C$_\alpha$ distance files
.list.caDists <- function() {
  list.files(pattern="*.dist_[[:digit:]]*_[[:digit:]]*$")
}
#' List specifically C$_\alpha$-distance PCA related files
.list.caPCA <- function() {
  ca_dist_files <- .list.caDists()
  caPCA <- list()
  for (f in ca_dist_files) {
    suffix <- strsplit(f, ".", fixed=TRUE)[[1]]
    suffix <- suffix[length(suffix)]
    caPCA[[suffix]] <- .list.PCA(f)
  }

  caPCA
}
#' List files with filtered reaction coordinates
.list.reactionCoords <- function() {
  list.files(pattern = "reaction_coords_[[:digit:]]+.coords$")
}

.check.projectPath <- function() {
  if (exists("path", envir=.project_cache, inherits=FALSE)) {
    path <- get("path", envir=.project_cache)
    if (getwd() != path) {
      warning(.warnings$diverging_path)
      setwd(path)
    }
  } else {
    warning(.warnings$no_init)
  }
  NULL
}

#' update project information
.update <- function() {
  .check.projectPath()

  project <- list()
  project$ref <- .list.reference()
  project$traj <- .list.traj()
  project$dihedrals <- .list.dihedrals()
  project$dPCAplus <- .list.dPCAplus()
  project$caDists <- .list.caDists()
  project$caPCA <- .list.caPCA()
  project$reactionCoords <- .list.reactionCoords()

  assign("project", project, envir=.project_cache)
}

#' initialize project
#'
#' Switches to given path and initializes prodyna-project.
#' Existing files are detected and any new files generated by
#' prodyna will be created under this directory.
#'
#' @export
initialize <- function(path=".") {
  assign("path",
         normalizePath(path),
         envir=.project_cache)
  .update()
}

