# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute ACF of circular data
#'
#' Computes the autocorrelation of circular data,
#' **defined on the range [-pi, pi], expressed in radians.**
#' ACF is computed in 'cov'-type.
#' @param x The input data.
#' @param tau_max The max correlation lag.
circacf <- function(x, tau_max) {
    .Call('prodyna_circacf', PACKAGE = 'prodyna', x, tau_max)
}

#' Compute ACF using OpenMP
#'
#' ACF is computed in 'cov'-type.
#' @param x The input data.
#' @param tau_max The max correlation lag.
fastacf <- function(x, tau_max) {
    .Call('prodyna_fastacf', PACKAGE = 'prodyna', x, tau_max)
}

#' Compute RGB color code from sampling of Ramachandran plot
#'
#' phi and psi values are defined on range [-180, 180].
#' @param phis Sampling of phi values.
#' @param psis Sampling of psi values.
rama2rgb <- function(phis, psis) {
    .Call('prodyna_rama2rgb', PACKAGE = 'prodyna', phis, psis)
}

#' computes a cos/sin transform of angles on the fly
#'
#' @param fname_in Input filename with angles.
#' @param fname_out Output filename with cos/sin transformed values.
#' @param is_deg Angles are expressed in degrees. default: true.
streamed_cossin_transform <- function(fname_in, fname_out, is_deg = TRUE) {
    invisible(.Call('prodyna_streamed_cossin_transform', PACKAGE = 'prodyna', fname_in, fname_out, is_deg))
}

