# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute ACF of circular data
#'
#' Computes the autocorrelation of circular data,
#' **defined on the range [0, 2pi], expressed in radians.**
#' ACF is computed in 'cov'-type.
#' @param x The input data.
#' @param tau_max The max correlation lag.
circacf <- function(x, tau_max) {
    .Call('prodyna_circacf', PACKAGE = 'prodyna', x, tau_max)
}

#' Compute ACF using OpenMP
#'
#' ACF is computed in 'cov'-type.
#' @param x The input data.
#' @param tau_max The max correlation lag.
fastacf <- function(x, tau_max) {
    .Call('prodyna_fastacf', PACKAGE = 'prodyna', x, tau_max)
}

